name: CD
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend ./backend
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend ./frontend
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/backend
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend
